<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation=
                   "http://ant.apache.org/ivy/schemas/ivy.xsd">
    <info organisation="myorg"
          module="mymodule"/>
    
    <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
    <dependencies>
        <dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="2.17.3"/>
        <dependency org="jakarta.persistence" name="jakarta.persistence-api" rev="3.1.0"/>
        <dependency org="org.hsqldb" name="hsqldb" rev="2.7.4"/>
        <dependency org="org.springframework" name="spring-orm" rev="5.3.36"/>
    </dependencies>
    
</ivy-module>